# Generated by Django 4.0.2 on 2023-08-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newrup1', '0003_partner_alter_services_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='img',
            field=models.ImageField(upload_to='partner'),
        ),
    ]
