# Generated by Django 4.0.2 on 2023-08-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newrup1', '0004_alter_partner_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='testimonial')),
                ('name', models.CharField(max_length=50)),
                ('pos', models.CharField(max_length=50)),
                ('des', models.TextField()),
            ],
        ),
    ]
