# Generated by Django 4.0.2 on 2023-08-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newrup1', '0005_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achivement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='achivement')),
                ('topic', models.CharField(max_length=60)),
                ('date', models.DateTimeField(null=True)),
                ('link', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='photo')),
                ('topic', models.CharField(max_length=60)),
                ('date', models.DateTimeField(null=True)),
                ('link', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='product')),
                ('topic', models.CharField(max_length=60)),
                ('date', models.DateTimeField(null=True)),
                ('link', models.CharField(max_length=500, unique=True)),
            ],
        ),
    ]
