# Generated by Django 4.0.2 on 2023-08-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newrup1', '0007_alter_achivement_link_alter_photo_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achivement',
            name='link',
            field=models.CharField(blank=True, default='', max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='link',
            field=models.CharField(blank=True, default='', max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.CharField(blank=True, default='', max_length=500, unique=True),
        ),
    ]
