# Generated by Django 4.0.2 on 2023-08-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newrup1', '0009_alter_testimonial_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
