# Generated by Django 4.0.2 on 2023-08-04 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newrup1', '0010_alter_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='photo')),
                ('des', models.TextField()),
            ],
        ),
    ]
