# Generated by Django 4.0.2 on 2023-08-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newrup1', '0013_alter_achivement_link_alter_photo_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=500, unique=True)),
            ],
        ),
    ]
