# Generated by Django 4.0.2 on 2023-08-04 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newrup1', '0014_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
