# Generated by Django 3.2.20 on 2023-08-04 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newrup1', '0016_slider'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slider',
            new_name='Track',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='img',
            new_name='image_uplod',
        ),
    ]
