# Generated by Django 3.2.20 on 2023-08-04 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newrup1', '0018_alter_contact_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='image_uplod',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='track',
            name='key',
        ),
    ]
